# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-24 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Arms', (('curl', 'Biceps Curl'), ('press', 'Shoulder Press'))), ('Legs', (('press', 'Leg Press'), ('curl', 'Leg Curl'), ('extension', 'Leg Extension'))), ('Chest', (('press', 'Chest Press'), ('fly', 'Chest Flys'))), ('unknown', 'Unknown')], max_length=100)),
                ('max_weight', models.PositiveSmallIntegerField()),
                ('num_sets', models.PositiveSmallIntegerField()),
                ('reps_per_set', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
