# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-24 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymtrack', '0002_auto_20170523_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='workout',
            name='gym_name',
        ),
        migrations.AddField(
            model_name='workout',
            name='gym',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gymtrack.Gym'),
            preserve_default=False,
        ),
    ]
