# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-24 04:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtrack', '0004_auto_20170523_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0, 1200)),
        ),
    ]
