# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymtrack', '0005_exercise_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='exercises',
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gymtrack.Workout'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(choices=[('Arms', (('bicurl', 'Biceps Curl'), ('armpress', 'Shoulder Press'), ('tricurl', 'Triceps Curl'))), ('Legs', (('legpress', 'Leg Press'), ('legcurl', 'Leg Curl'), ('legext', 'Leg Extension'), ('abduction', 'Leg Abduction'), ('adduction', 'Leg Adduction'))), ('Chest', (('chestpress', 'Chest Press'), ('chestfly', 'Chest Flys'))), ('abs', 'Abdominal Crunches'), ('cardio', 'Cardio Exercise'), ('unknown', 'Unknown')], max_length=100),
        ),
    ]
