# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtrack', '0006_auto_20170525_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='workout',
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(to='gymtrack.Exercise'),
        ),
    ]
