# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-28 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtrack', '0010_workout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='max_weight',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
