# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-28 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtrack', '0011_auto_20170528_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='num_sets',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='reps_per_set',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
